'use strict';
const http=require('http'); const {URL}=require('url'); const registry=require('./registry'); const keychain=require('./keychain'); const ui=require('./ui'); const shopee=require('./shopee'); const facebook=require('./facebook');
const DEFAULT_HOST='127.0.0.1', DEFAULT_PORT=8840; const CSP="default-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'";
function send(res,status,obj){const body=JSON.stringify(obj); res.writeHead(status,{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store'}); res.end(body)}
function html(res,body){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Content-Security-Policy':CSP,'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Cache-Control':'no-store'}); res.end(body)}
function parse(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',d=>{raw+=d;if(raw.length>1e6)reject(Object.assign(new Error('body_too_large'),{status:413}))});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(Object.assign(new Error('invalid_json'),{status:400}))}});req.on('error',reject)})}
async function redactedAccounts(configPath,kc=keychain){const rows=await registry.list(configPath); return Promise.all(rows.map(async r=>Object.assign({},r,await kc.status(r.provider,r.account))))}
function createServer(opts={}){const configPath=opts.configPath; const kc=opts.keychain||keychain; return http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1'); if(req.method==='GET'&&url.pathname==='/') return html(res,ui.page()); if(req.method==='GET'&&url.pathname==='/health') return send(res,200,{status:'ok',service:'affiliate-credential-vault',port:DEFAULT_PORT,keychainSupported:kc.isSupported()}); if(req.method==='GET'&&url.pathname==='/accounts') return send(res,200,{ok:true,accounts:await redactedAccounts(configPath,kc)}); if(req.method==='POST'&&url.pathname==='/accounts'){const body=await parse(req); const {password,totp,...metadata}=body; const rec=await registry.upsert(metadata,configPath); const secrets={passwordPresent:false,totpPresent:false}; if(password) secrets.passwordPresent=(await kc.saveSecret(rec.provider,rec.account,'password',password)).saved; if(totp) secrets.totpPresent=(await kc.saveSecret(rec.provider,rec.account,'totp',totp)).saved; return send(res,200,{ok:true,account:rec,secrets:Object.assign(await kc.status(rec.provider,rec.account),secrets)}); } if(req.method==='DELETE'&&url.pathname==='/accounts'){const provider=url.searchParams.get('provider'); const account=url.searchParams.get('account'); const out=await registry.remove(provider,account,configPath); await kc.purge(out.provider,out.account); return send(res,200,Object.assign({ok:true},out));} if(req.method==='GET'&&url.pathname==='/facebook/health') return send(res,200,await facebook.fetchHealth()); if(req.method==='POST'&&url.pathname==='/facebook/login'){const body=await parse(req); return send(res,200,{ok:true,openUrl:facebook.loginUrl(body.account)});} if(req.method==='POST'&&url.pathname==='/shopee/login'){const body=await parse(req); return send(res,200,Object.assign({ok:true},shopee.openLogin(body)));} if(req.method==='POST'&&url.pathname==='/shopee/shorten'){const body=await parse(req); return send(res,200,await shopee.shorten(body));} return send(res,404,{ok:false,error:'not_found'});}catch(e){return send(res,e.status||500,{ok:false,error:e.message})}})}
function start({port=DEFAULT_PORT,host=DEFAULT_HOST}={}){const s=createServer(); s.listen(port,host,()=>console.log(`[affiliate-credential-vault] listening on http://${host}:${port}`)); return s}
module.exports={createServer,start,CSP};
