'use strict';
const path = require('path');
const os = require('os');
const childProcess = require('child_process');
const http = require('http');
const DASHBOARD_URL = 'https://affiliate.shopee.co.th/dashboard';
function profileRoot(){ return process.env.AFFILIATE_CREDENTIAL_VAULT_PROFILE_DIR || path.join(os.homedir(), '.affiliate-credential-vault', 'profiles'); }
function safeAlias(v){ return String(v||'').trim().replace(/[^A-Za-z0-9._-]/g,'_').slice(0,80) || 'default'; }
function chromiumApp(){ return process.env.AFFILIATE_CREDENTIAL_VAULT_CHROMIUM_APP || '/Users/yok-macmini/.cloakbrowser/chromium-145.0.7632.109.2/Chromium.app'; }
function openLogin({account, profileAlias, url=DASHBOARD_URL}={}){ const alias=safeAlias(profileAlias||account); const profileDir=path.join(profileRoot(),'shopee',alias); const app=chromiumApp(); const args=['-na',app,'--args',`--user-data-dir=${profileDir}`,'--no-first-run','--new-window',url]; const p=childProcess.spawn('/usr/bin/open', args, {stdio:'ignore', detached:true}); p.unref(); return { opened:true, account: safeAlias(account||alias), profileAlias: alias, profileDir, url }; }
function buildShopeeShortenUrl(body={}, base='http://127.0.0.1:8810/shorten'){ const productUrl=String(body.productUrl||body.url||'').trim(); if(!productUrl) throw new Error('Missing productUrl'); const alias=String(body.profileAlias||body.account||'').trim(); const u=new URL(base); u.searchParams.set('platform','shopee'); u.searchParams.set('url',productUrl); if(alias) u.searchParams.set('account', alias); const affiliateId=String(body.affiliateId||body.id||'').trim(); if(affiliateId && (body.includeAffiliateId===true || !alias)) u.searchParams.set('id', affiliateId); for(const k of ['sub1','sub2','sub3','sub4','sub5']){ if(body[k]!=null && String(body[k]).trim()) u.searchParams.set(k,String(body[k]).trim()); } return u.toString(); }
function fetchJson(url, timeoutMs=120000){ return new Promise((resolve)=>{ const req=http.get(url,{timeout:timeoutMs},res=>{ let raw=''; res.on('data',d=>raw+=d); res.on('end',()=>{ let json=null; try{json=JSON.parse(raw)}catch{} resolve({statusCode:res.statusCode, json, raw: raw.slice(0,500)}); }); }); req.on('timeout',()=>{req.destroy(new Error('timeout'))}); req.on('error',e=>resolve({statusCode:0, json:{error:'bridge_unavailable', reason:e.message}})); }); }
function sanitizeBridgePayload(payload){ const src=payload&&typeof payload==='object'?payload:{}; const out={}; for(const k of ['status','ok','reason','error','message','loginUi','account','platform','shortLink','short_link','shortUrl','url']) if(src[k]!=null) out[k]=src[k]; return out; }
async function shorten(body, opts={}){ const target=buildShopeeShortenUrl(body, opts.base); const res=await fetchJson(target, opts.timeoutMs); return { ok: !!(res.json && (res.json.shortLink||res.json.short_link||res.json.shortUrl)), statusCode: res.statusCode, target: target.replace(/url=[^&]+/,'url=[REDACTED]'), result: sanitizeBridgePayload(res.json||{}) }; }
module.exports={DASHBOARD_URL, profileRoot, safeAlias, openLogin, buildShopeeShortenUrl, sanitizeBridgePayload, shorten};
