name = "neezs-shopee-shortlink"
main = "../worker/src/index.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "BRIDGE"
class_name = "BridgeDO"

[[migrations]]
tag = "v1"
new_classes = ["BridgeDO"]
