'use strict';
const path=require('path'); const os=require('os'); const {sanitizeAccount}=require('./accounts');
const PROFILE_ROOT=process.env.FACEBOOK_TOKEN_CLOAK_PROFILE_ROOT||path.join(os.homedir(),'.facebook-token-cloak','profiles');
async function loadBrowserBackend(){ try{const cloak=require('cloakbrowser'); if(cloak&&typeof cloak.launchPersistentContext==='function') return {backend:'cloakbrowser',launcher:cloak};}catch{} try{const {chromium}=require('playwright-core'); return {backend:'playwright-core',launcher:chromium};}catch{} throw Object.assign(new Error('No browser backend found. Install cloakbrowser or playwright-core.'),{code:'browser_backend_missing'}); }
function profileDirFor(accountKey){return path.join(PROFILE_ROOT,accountKey)}
async function launchPersistentContext(rawAccount,options={}){ const {key}=sanitizeAccount(rawAccount); const {backend,launcher}=await loadBrowserBackend(); const profileDir=profileDirFor(key); const context=await launcher.launchPersistentContext(profileDir,{headless:options.visible===false,args:['--disable-blink-features=AutomationControlled','--no-first-run','--no-default-browser-check'],...options.launchOptions}); return {backend,profileDir,context}; }
async function openPage(rawAccount,url,options={}){ const launched=await launchPersistentContext(rawAccount,options); const page=(launched.context.pages&&launched.context.pages()[0])||await launched.context.newPage(); await page.goto(url,{waitUntil:'domcontentloaded',timeout:options.timeoutMs||60000}); return {...launched,page}; }
async function fillFacebookLogin(page,credential,{submit=false}={}){ if(!credential||!credential.username||!credential.password) return {autofilled:false,submitted:false}; await page.fill('input[name="email"], input#email',credential.username).catch(()=>{}); await page.fill('input[name="pass"], input#pass',credential.password).catch(()=>{}); if(submit) await page.click('button[name="login"], input[name="login"], [type="submit"]').catch(()=>{}); return {autofilled:true,submitted:!!submit}; }
module.exports={PROFILE_ROOT,loadBrowserBackend,profileDirFor,launchPersistentContext,openPage,fillFacebookLogin};
