'use strict';
// Historical Postcron OAuth is retired. Keep the export name for compatibility with
// older call sites/tests, but open a first-party logged-in Facebook surface so the
// bridge can use the session-derived token extractor instead of any third-party app id.
const FACEBOOK_OAUTH_URL='https://adsmanager.facebook.com/adsmanager/manage/campaigns';
const GRAPH_PAGES_URL='https://graph.facebook.com/v19.0/me/accounts?fields=id,name,category,access_token&limit=200';
function extractAccessTokenFromUrl(url){ if(!url||typeof url!=='string') return null; const m=url.match(/[#&]access_token=([^&#\s]+)/); if(m) return decodeURIComponent(m[1]); try{return new URL(url).searchParams.get('access_token')}catch{const q=url.match(/[?&]access_token=([^&#\s]+)/); return q?decodeURIComponent(q[1]):null;} }
function sanitizePages(pages, includeToken=false){ if(!Array.isArray(pages)) return []; return pages.map(p=>{const out={id:p&&p.id!=null?String(p.id):undefined,name:p&&p.name!=null?String(p.name):undefined,category:p&&p.category!=null?String(p.category):undefined,hasToken:!!(p&&p.access_token)}; if(includeToken&&p&&p.access_token) out.access_token=String(p.access_token); return out;}); }
function classifyFacebookState(input={}){ const safe=input&&typeof input==='object'?input:{}; const {url='',bodyText=''}=safe; const text=`${url}\n${bodyText}`.toLowerCase(); if(extractAccessTokenFromUrl(url)) return 'has_token'; if(/checkpoint|checkpoint_required/.test(text)) return 'facebook_checkpoint'; if(/security confirmation|confirm your identity|secure your account/.test(text)) return 'facebook_security_confirmation'; if(/automated behavior|temporarily blocked|try again later/.test(text)) return 'facebook_automated_behavior'; if(/error=access_denied|oauth.*denied|not authorized|cancelled/.test(text)) return 'oauth_denied'; if(/login|เข้าสู่ระบบ|log in/.test(text)) return 'facebook_login_required'; return 'token_not_found'; }
function buildNoTokenRefreshResponse(account, reason='token_not_found'){ return {account,status:'no_token',tokenPresent:false,reason,refreshed:false,loginUrl:FACEBOOK_OAUTH_URL}; }
async function fetchPages(fetchImpl,userToken,includeToken=false){ const res=await fetchImpl(`${GRAPH_PAGES_URL}&access_token=${encodeURIComponent(userToken)}`); if(!res.ok) throw Object.assign(new Error(`Graph pages failed: ${res.status}`),{reason:'graph_pages_failed'}); const body=await res.json(); const pages=sanitizePages(body.data||[],includeToken); return {pages,pagesCount:pages.length}; }
module.exports={FACEBOOK_OAUTH_URL,GRAPH_PAGES_URL,extractAccessTokenFromUrl,sanitizePages,classifyFacebookState,buildNoTokenRefreshResponse,fetchPages};
