name = "token-facebook-lite"
main = "src/index.ts"
compatibility_date = "2026-02-28"
compatibility_flags = ["nodejs_compat"]

[[containers]]
class_name = "TokenFacebookLite"
image = "registry.cloudflare.com/bc9db0f4b48f964b6e445dccc240af87/token-facebook-lite:v1"
max_instances = 2
instance_type = "standard-1"

[[durable_objects.bindings]]
name = "TOKEN_FACEBOOK_LITE"
class_name = "TokenFacebookLite"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TokenFacebookLite"]
