name = "video-affiliate-worker-mergecontainer"
account_id = "bc047db265944dddff5f07cfa6ef45aa"
main = "src/main.rs"
compatibility_date = "2026-02-24"

[[containers]]
image = "registry.cloudflare.com/bc047db265944dddff5f07cfa6ef45aa/video-affiliate-worker-mergecontainer:v2026-03-29.01"
class_name = "MergeContainer"
